name: baby_sleep_time
description: Baby sleep time recorder
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  intro_views_flutter:
  google_fonts:
  font_awesome_flutter:
  cached_network_image:
  equatable:
  shared_preferences:
  table_calendar:
  circle_wave_progress:
  fl_chart:

  # Utils
  intl:
  path_provider:
  uuid:
  http:
  event_bus:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
