name: baby_sleep_time
description: Baby sleep time recorder
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart:
  intl:
  path_provider:
  floor: ^0.13.0
  sqflite: ^1.3.0

dev_dependencies:
  floor_generator: ^0.13.0
  build_runner: ^1.7.3
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/avatar.png"
